# Generated by Django 4.2.6 on 2023-10-18 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileApp', '0002_teacher_count_peaple_teacher_max_peaple_and_more'),
        ('CabinetApp', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cabinet',
            name='teachers',
        ),
        migrations.AddField(
            model_name='cabinet',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cabinets', to='ProfileApp.teacher'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='an_dellet',
            field=models.BooleanField(default=False),
        ),
    ]
