# Generated by Django 4.2.6 on 2023-10-16 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cabinet', '0003_schedule_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='an_dellet',
            field=models.BooleanField(default=False),
        ),
    ]
