# Generated by Django 4.2.6 on 2023-10-16 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0005_alter_teacher_description'),
        ('Cabinet', '0004_schedule_an_dellet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cabinet',
            name='teachers',
        ),
        migrations.AddField(
            model_name='cabinet',
            name='teacher',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cabinets', to='profileapp.teacher'),
        ),
    ]
