# Generated by Django 4.2.6 on 2023-10-17 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0005_alter_teacher_description'),
        ('Cabinet', '0005_remove_cabinet_teachers_cabinet_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinet',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cabinets', to='profileapp.teacher'),
        ),
    ]
