# Generated by Django 4.2.6 on 2023-10-22 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0005_alter_chat_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='quontity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
