# Generated by Django 4.2.6 on 2024-03-05 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileApp', '0009_service_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date_create'], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['is_published', 'is_pinned'], name='ProfileApp__is_publ_63f35c_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-date_create'], name='ProfileApp__date_cr_bde870_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['title', 'slug'], name='ProfileApp__title_5d7635_idx'),
        ),
    ]
